name: GenderPrefixes
main: sh.okx.genderprefixes.GenderPrefixes
author: Okx
version: 1.1
api-version: 1.15
depend: [LuckPerms]

commands:
  male:
    permission: gender.command
    description: Set your gender in prefixes as male
  female:
    permission: gender.command
    description: Set your gender in prefixes as female
